const Koa = require('koa')
const cors = require('@koa/cors')
const bodyParser = require('koa-bodyparser')
const jwt = require('koa-jwt')
const { auth } = require('./middleware/auth')
const jwtConfig = require('./config/jwt.json')
const router = require('./service')
const app = new Koa()

app.use(cors({ credentials: true }))
app.use(bodyParser())
app.use(jwt({ secret: jwtConfig.secret }).unless({ path: [/^\/v\d\/public/] }))
// app.use(auth)
app.use(router.routes())
app.use(router.allowedMethods())
app.listen(3000)
console.log('http://127.0.0.1:3000/')
