FORMAT: 1A

# ErIOT Example Server API

# Client API Root [/]

## Get client data [GET /client]
+ Response 200 (application/json)
    + Headers
        Authorization: <JWT>

## Get data by client [GET /]
+ Response 200 (application/json)
    + Headers
        Authorization: <JWT>
